export const PRODUCT_CATEGORIES = [
  "Action Figures",
  "Board Games",
  "Educational Toys",
  "Dolls",
  "Vehicles",
  "Puzzles",
  "Outdoor & Sports",
  "Arts & Crafts",
  "Battery Operated Toys",
  "Building Sets",
  "Return Gifts Toys",
  "Lunch Box And Bottles",
  "School Bags",
  "Return Gifts Stationary",
  "Non Battery Toys",
  "Soft Toys",
  "New Arrivals",
  "Stanley",
  "Kpop",
  "Harry Potter",
  "Minecraft (Lego)",
  "Keychain",
  "Diy",
  "Swimming",
  "Bags",
];
