export const CATEGORIES = [
  "Action Figures",
  "Board Games",
  "Educational Toys",
  "Dolls",
  "Vehicles",
  "Puzzles",
  "Outdoor & Sports",
  "Arts & Crafts",
  "Battery Operated Toys",
  "Building Sets",
  "Return Gifts Toys",
  "Lunch Box And Bottles",
  "School Bags",
  "Return Gifts Stationary",
  "Non Battery Toys",
  "Soft Toys",
];

export const CATEGORY_EMOJIS = {
  "Action Figures": "🦸",
  "Board Games": "♟️",
  "Educational Toys": "📚",
  Dolls: "🪆",
  Vehicles: "🚗",
  Puzzles: "🧩",
  "Outdoor & Sports": "⚽",
  "Arts & Crafts": "🎨",
  "Battery Operated Toys": "🔋",
  "Building Sets": "🧱",
  "Return Gifts Toys": "🎁",
  "Lunch Box And Bottles": "🥤",
  "School Bags": "🎒",
  "Return Gifts Stationary": "✏️",
  "Non Battery Toys": "🪀",
  "Soft Toys": "🧸",
};
